pipeline {
  agent any

  tools {
    maven 'Maven 3.8.7'
  }

  environment {
    IMAGE_NAME = 'rramm/my-java-app'
    IMAGE_TAG  = "${env.BUILD_NUMBER}"
    DOCKERHUB_CREDENTIALS = 'dockerhub-creds'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
        sh 'ls -R .'
      }
    }

    stage('Build & Push') {
      steps {
        dir('my-java-app') {
          sh 'ls -R .'
          sh 'mvn clean package -DskipTests'

          script {
            docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
            docker.withRegistry('https://registry.hub.docker.com', DOCKERHUB_CREDENTIALS) {
              docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
              docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push('latest')
            }
          }
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
